# Generated by Django 5.0 on 2024-08-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animais", "0003_denuncia_alter_apreensaoanimal_bairro_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgendaCastracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("telefone", models.CharField(max_length=20)),
                (
                    "animal_de_grande_porte",
                    models.CharField(
                        choices=[
                            ("Cavalo", "Cavalo"),
                            ("Boi", "Boi"),
                            ("Porco", "Porco"),
                        ],
                        max_length=6,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgendaConsulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("telefone", models.CharField(max_length=20)),
                (
                    "animal_de_grande_porte",
                    models.CharField(
                        choices=[
                            ("Cavalo", "Cavalo"),
                            ("Boi", "Boi"),
                            ("Cabra", "Cabra"),
                            ("Porco", "Porco"),
                        ],
                        max_length=6,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HospitalVeterinario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("telefone", models.CharField(max_length=20)),
                (
                    "animal_de_grande_porte",
                    models.CharField(
                        choices=[
                            ("Cavalo", "Cavalo"),
                            ("Boi", "Boi"),
                            ("Cabra", "Cabra"),
                            ("Porco", "Porco"),
                        ],
                        max_length=6,
                    ),
                ),
            ],
        ),
    ]
