# Generated by Django 5.0 on 2024-08-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animais", "0004_agendacastracao_agendaconsulta_hospitalveterinario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendacastracao",
            name="animal_de_grande_porte",
            field=models.CharField(
                choices=[
                    ("Cavalo", "Cavalo"),
                    ("Boi", "Boi"),
                    ("Cabra", "Cabra"),
                    ("Porco", "Porco"),
                ],
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="agendacastracao",
            name="telefone",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="agendaconsulta",
            name="telefone",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="apreensaoanimal",
            name="animal_de_grande_porte",
            field=models.CharField(
                choices=[
                    ("Cavalo", "Cavalo"),
                    ("Boi", "Boi"),
                    ("Cabra", "Cabra"),
                    ("Porco", "Porco"),
                ],
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="apreensaoanimal",
            name="bairro",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="apreensaoanimal",
            name="cep",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="apreensaoanimal",
            name="cidade",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="apreensaoanimal",
            name="estado",
            field=models.CharField(
                choices=[
                    ("AC", "Acre"),
                    ("AL", "Alagoas"),
                    ("AP", "Amapá"),
                    ("AM", "Amazonas"),
                    ("BA", "Bahia"),
                    ("CE", "Ceará"),
                    ("DF", "Distrito Federal"),
                    ("ES", "Espírito Santo"),
                    ("GO", "Goiás"),
                    ("MA", "Maranhão"),
                    ("MT", "Mato Grosso"),
                    ("MS", "Mato Grosso do Sul"),
                    ("MG", "Minas Gerais"),
                    ("PA", "Pará"),
                    ("PB", "Paraíba"),
                    ("PR", "Paraná"),
                    ("PE", "Pernambuco"),
                    ("PI", "Piauí"),
                    ("RJ", "Rio de Janeiro"),
                    ("RN", "Rio Grande do Norte"),
                    ("RS", "Rio Grande do Sul"),
                    ("RO", "Rondônia"),
                    ("RR", "Roraima"),
                    ("SC", "Santa Catarina"),
                    ("SP", "São Paulo"),
                    ("SE", "Sergipe"),
                    ("TO", "Tocantins"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="apreensaoanimal",
            name="numero",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="apreensaoanimal",
            name="rua",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="apreensaoanimal",
            name="telefone",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="coletaanimaismortos",
            name="bairro",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="coletaanimaismortos",
            name="cep",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="coletaanimaismortos",
            name="cidade",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="coletaanimaismortos",
            name="estado",
            field=models.CharField(
                choices=[
                    ("AC", "Acre"),
                    ("AL", "Alagoas"),
                    ("AP", "Amapá"),
                    ("AM", "Amazonas"),
                    ("BA", "Bahia"),
                    ("CE", "Ceará"),
                    ("DF", "Distrito Federal"),
                    ("ES", "Espírito Santo"),
                    ("GO", "Goiás"),
                    ("MA", "Maranhão"),
                    ("MT", "Mato Grosso"),
                    ("MS", "Mato Grosso do Sul"),
                    ("MG", "Minas Gerais"),
                    ("PA", "Pará"),
                    ("PB", "Paraíba"),
                    ("PR", "Paraná"),
                    ("PE", "Pernambuco"),
                    ("PI", "Piauí"),
                    ("RJ", "Rio de Janeiro"),
                    ("RN", "Rio Grande do Norte"),
                    ("RS", "Rio Grande do Sul"),
                    ("RO", "Rondônia"),
                    ("RR", "Roraima"),
                    ("SC", "Santa Catarina"),
                    ("SP", "São Paulo"),
                    ("SE", "Sergipe"),
                    ("TO", "Tocantins"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="coletaanimaismortos",
            name="numero",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="coletaanimaismortos",
            name="rua",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="coletaanimaismortos",
            name="telefone",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="denuncia",
            name="cep",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="hospitalveterinario",
            name="telefone",
            field=models.CharField(max_length=15),
        ),
    ]
