# Generated by Django 5.0 on 2024-08-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plantio_de_Arvores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("larg_compr_calcada", models.CharField(max_length=100)),
                ("observacoes", models.TextField()),
                ("cep", models.IntegerField()),
                ("bairro", models.CharField(max_length=100)),
                ("nome_rua", models.CharField(max_length=100)),
                ("ponto_refer", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Poda_de_Arvores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rua", models.CharField(max_length=100)),
                ("numero", models.IntegerField()),
                ("bairro", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=2)),
                ("cidade", models.CharField(max_length=100)),
                ("cep", models.IntegerField()),
                ("ponto_refer", models.CharField(max_length=100)),
                ("observacoes", models.TextField(max_length=100)),
                ("telefone", models.IntegerField()),
            ],
        ),
    ]
