# Generated by Django 5.1 on 2024-08-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meio_ambiente", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="corte_irregular_arvores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observacoes", models.TextField()),
                ("cep_problema", models.IntegerField()),
                ("bairro_problema", models.CharField(max_length=200)),
                ("rua_problema", models.CharField(max_length=200)),
                ("ponto_refer", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="invasao_area_preservacao_permanente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observacoes", models.TextField()),
                ("cep_problema", models.IntegerField()),
                ("bairro_problema", models.CharField(max_length=200)),
                ("rua_problema", models.CharField(max_length=200)),
                ("ponto_refer", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="lancamento_de_agua_servidas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cep_problema", models.IntegerField()),
                ("bairro_problema", models.CharField(max_length=200)),
                ("rua_problema", models.CharField(max_length=200)),
                ("ponto_refer", models.TextField()),
                ("observacoes", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="lancamento_esgoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cep_problema", models.IntegerField()),
                ("bairro_problema", models.CharField(max_length=200)),
                ("rua_problema", models.CharField(max_length=200)),
                ("ponto_refer", models.TextField()),
                ("observacoes", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="poluicao_atmosferica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observacoes", models.TextField()),
                ("cep_problema", models.IntegerField()),
                ("bairro_problema", models.CharField(max_length=200)),
                ("rua_problema", models.CharField(max_length=200)),
                ("ponto_refer", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="poluicao_sonora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observacoes", models.TextField()),
                ("cep_problema", models.IntegerField()),
                ("bairro_problema", models.CharField(max_length=200)),
                ("rua_problema", models.CharField(max_length=200)),
                ("ponto_refer", models.TextField()),
            ],
        ),
    ]
