# Generated by Django 5.0 on 2024-09-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meio_ambiente", "0002_corte_irregular_arvores_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantio_de_arvores",
            name="status",
            field=models.CharField(default="", max_length=100),
        ),
    ]
