from django.contrib import admin
from .models import Conselho_tutelar_cristo, Conselho_tutelar_mangabeira, Conselho_tutelar_norte, Conselho_tutelar_praia, Conselho_tutelar_sudeste, Conselho_tutelar_sul, Conselho_tutelar_valentina, Funjope_Apoio_a_eventos_artisticos, Funjope_atestado_da_condicao_de_artista_local, Funjope_cadastramento_de_artistas_e_outros, Funjope_concertos_de_orquestra_sinfonica, Funjope_exposicao_de_artes_visuais, Funjope_edital_de_ocupacao_do_casa_da_polvora, Funjope_edital_de_ocupacao_do_casarao_34, Funjope_edital_de_ocupacao_do_hotel_globo, Funjope_instalacao_de_obras_de_arte, Funjope_jp_cultura, Funjope_jp_film_commission, Funjope_lei_dos_edificios, Funjope_prestacao_de_contas, Funjope_projeto_acao_social_pela_musica, Funjope_solicitacao_de_pagamento, Ptts_ouvidoria_maria_de_nazare, Familia_acolhedora_forms

# Register your models here.



admin.site.register(Funjope_Apoio_a_eventos_artisticos)
admin.site.register(Funjope_atestado_da_condicao_de_artista_local)
admin.site.register(Funjope_cadastramento_de_artistas_e_outros)
admin.site.register(Funjope_concertos_de_orquestra_sinfonica)
admin.site.register(Funjope_exposicao_de_artes_visuais)
admin.site.register(Funjope_edital_de_ocupacao_do_casa_da_polvora)
admin.site.register(Funjope_edital_de_ocupacao_do_casarao_34)
admin.site.register(Funjope_edital_de_ocupacao_do_hotel_globo)
admin.site.register(Funjope_instalacao_de_obras_de_arte)
admin.site.register(Funjope_jp_cultura)
admin.site.register(Funjope_jp_film_commission)
admin.site.register(Funjope_lei_dos_edificios)
admin.site.register(Funjope_prestacao_de_contas)
admin.site.register(Funjope_projeto_acao_social_pela_musica)
admin.site.register(Funjope_solicitacao_de_pagamento)

admin.site.register(Conselho_tutelar_cristo)
admin.site.register(Conselho_tutelar_mangabeira)
admin.site.register(Conselho_tutelar_norte)
admin.site.register(Conselho_tutelar_praia)
admin.site.register(Conselho_tutelar_sudeste)
admin.site.register(Conselho_tutelar_sul)
admin.site.register(Conselho_tutelar_valentina)

admin.site.register(Ptts_ouvidoria_maria_de_nazare)

admin.site.register(Familia_acolhedora_forms)






