# Generated by Django 5.0 on 2024-08-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recebimento_de_Convite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
            ],
            options={
                "verbose_name": "SEJER - Recebimento_de_Convite",
            },
        ),
        migrations.CreateModel(
            name="Solicitacao_de_Apoio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
            ],
            options={
                "verbose_name": "SEJER - Solicitacao_de_Apoio",
            },
        ),
        migrations.CreateModel(
            name="Solicitacao_de_Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
            ],
            options={
                "verbose_name": "SEJER - Solicitacao_de_Material",
            },
        ),
        migrations.CreateModel(
            name="Solicitacao_de_Reparos_e_Manutencao_de_Equipamentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
            ],
            options={
                "verbose_name": "SEJER - Solicitacao_de_Reparos_e_Manutencao_de_Equipamentos",
            },
        ),
        migrations.CreateModel(
            name="Solicitacao_de_Uso_de_Espaco_Fisico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
            ],
            options={
                "verbose_name": "SEJER - Solicitacao_de_Uso_de_Espaco_Fisico",
            },
        ),
    ]
