# Generated by Django 5.0 on 2024-09-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esporte", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aberto", models.CharField(max_length=200)),
                ("em_andamento", models.CharField(max_length=200)),
                ("fechado", models.CharField(max_length=200)),
            ],
        ),
    ]
