# Generated by Django 5.0 on 2024-09-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esporte", "0002_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Status",
        ),
        migrations.AddField(
            model_name="recebimento_de_convite",
            name="status",
            field=models.CharField(default="aberto", max_length=200),
        ),
    ]
