# Generated by Django 5.0 on 2024-09-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educacao", "0003_autorizacao_de_estagio_supervisionado_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="autorizacao_para_pesquisa_crei_escola",
            name="status",
            field=models.CharField(
                choices=[
                    ("ABERTO", "Aberto"),
                    ("ANDAMENTO", "Em Andamento"),
                    ("FECHADO", "Fechado"),
                ],
                default="Aberto",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="furto_extravio_ou_perda_de_equipamentos",
            name="status",
            field=models.CharField(
                choices=[
                    ("ABERTO", "Aberto"),
                    ("ANDAMENTO", "Em Andamento"),
                    ("FECHADO", "Fechado"),
                ],
                default="Aberto",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="solicitacao_de_espaco_fisico_escola_crei",
            name="status",
            field=models.CharField(
                choices=[
                    ("ABERTO", "Aberto"),
                    ("ANDAMENTO", "Em Andamento"),
                    ("FECHADO", "Fechado"),
                ],
                default="Aberto",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="solicitacao_diversa",
            name="status",
            field=models.CharField(
                choices=[
                    ("ABERTO", "Aberto"),
                    ("ANDAMENTO", "Em Andamento"),
                    ("FECHADO", "Fechado"),
                ],
                default="Aberto",
                max_length=30,
            ),
        ),
    ]
