# Generated by Django 5.1 on 2024-08-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenciamento", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sedrub",
            name="CPF",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sedrub",
            name="Endereco",
            field=models.TextField(default="Seu endereco"),
        ),
        migrations.AddField(
            model_name="sedrub",
            name="Ligação_de_Energia",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sedrub",
            name="Ligação_de_Água",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sedrub",
            name="Requerente",
            field=models.TextField(default="Seu nome"),
        ),
    ]
