# Generated by Django 5.1 on 2024-08-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenciamento", "0003_alter_sedrub_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sedrub",
            name="Descricao",
            field=models.TextField(default="Conteúdo"),
        ),
        migrations.AlterField(
            model_name="sedrub",
            name="Endereco",
            field=models.TextField(),
        ),
    ]
