# Generated by Django 5.1 on 2024-08-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "licenciamento",
            "0007_alter_autorização_uso_de_solo_eventual_requerente_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="autorização_uso_de_solo_eventual",
            name="Requerente",
        ),
        migrations.AlterField(
            model_name="sedrub",
            name="Endereco",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="sedrub",
            name="Requerente",
            field=models.TextField(default=None),
        ),
    ]
