# Generated by Django 5.1 on 2024-08-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("licenciamento", "0014_atualização_cadatral_dos_quiosques"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Atualização_Cadatral_Dos_Quiosques",
            new_name="Atualizacao_Cadatral_Dos_Quiosques",
        ),
        migrations.RenameModel(
            old_name="Autorização_Uso_de_Solo_Eventual",
            new_name="Autorizacao_Uso_de_Solo_Eventual",
        ),
    ]
