# Generated by Django 5.1 on 2024-08-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenciamento", "0021_iptu_isencao_imoveis_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ISS_Reduçãode_Alíquota_ISS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Descricao", models.TextField()),
            ],
        ),
    ]
