# Generated by Django 5.1 on 2024-08-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("licenciamento", "0022_iss_reduçãode_alíquota_iss"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="IPTU_Isencao_Imoveis",
            new_name="IPTU_Isencao_de_Imoveis",
        ),
    ]
