# Generated by Django 5.0.2 on 2024-08-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eletricos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=15)),
                ('observacoes', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pontoReferencia', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('nome_Area_publica', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expansao_iluminacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontoReferencia', models.CharField(max_length=100)),
                ('expansao_iluminacao', models.CharField(choices=[('Ausencia de Poste', 'Ausencia de Poste'), ('Iluminação Inexistente', 'Iluminação Inexistente')], max_length=30)),
                ('rua', models.CharField(max_length=100)),
                ('numeroRecidencia', models.ImageField(upload_to='')),
                ('bairro', models.CharField(max_length=100)),
                ('estadoUF', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('cidade', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('observacoes', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='GaleriaBocaLobo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontoReferencia', models.CharField(max_length=100)),
                ('problema_Drenagem', models.CharField(choices=[('Tampa/Grelha Quebrado', 'Tampa/Grelha Quebrado'), ('Afundamento do Terreno', 'Afundamento do Terreno'), ('Alagamento', 'Alagamento'), ('Desobstrucao E Limpeza', 'Desobstrucao E Limpeza')], max_length=40)),
                ('observacoes', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('telefone', models.CharField(max_length=15)),
                ('rua', models.CharField(max_length=100)),
                ('numeroRecidencia', models.ImageField(upload_to='')),
                ('bairro', models.CharField(max_length=100)),
                ('estadoUF', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('cidade', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hidraulicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=15)),
                ('observacoes', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pontoReferencia', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('nome_Area_publica', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jardinagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=15)),
                ('observacoes', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pontoReferencia', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('nome_Area_publica', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mercenaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=10)),
                ('telefone', models.CharField(max_length=15)),
                ('observacoes', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pontoReferencia', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pinturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=15)),
                ('observacoes', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pontoReferencia', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('nome_Area_publica', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Problema_iluminacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_iluminacao', models.CharField(choices=[('L', 'LED'), ('C', 'Convencional')], max_length=15)),
                ('qual_problema_iluminacao', models.CharField(choices=[('A', 'Apagada'), ('A24h', 'Acesa 24hr'), ('I', 'Intermitente(Piscando)'), ('P', 'Poste Caído'), ('F', 'Fios Caído')], max_length=30)),
                ('observacoes', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
                ('numeroRecidencia', models.ImageField(upload_to='')),
                ('cep', models.CharField(max_length=10)),
                ('pontoReferencia', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SEMOB_Apoio_Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SEMOB_Baixa_Certidoes_IPI_ICMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SEMOB_Baixa_multa_deferimento_recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SEMOB_Baixa_multa_transito_pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SEMOB_Baixa_multa_transporte_pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SEMOB_Cadastro_Acompanhante_Escolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Serralharia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=15)),
                ('observacoes', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pontoReferencia', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('nome_Area_publica', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tapa_buraco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontoReferencia', models.CharField(max_length=100)),
                ('tipo_pavimentacao', models.CharField(choices=[('Asfalto', 'Asfalto'), ('Paralelepípedo', 'Paralelepípedo'), ('Barro', 'Barro')], max_length=30)),
                ('observacoes', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('telefone', models.CharField(max_length=15)),
                ('rua', models.CharField(max_length=100)),
                ('numeroRecidencia', models.ImageField(upload_to='')),
                ('bairro', models.CharField(max_length=100)),
                ('estadoUF', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('cidade', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Terraplanagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontoReferencia', models.CharField(max_length=100)),
                ('observacoes', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('telefone', models.CharField(max_length=15)),
                ('rua', models.CharField(max_length=100)),
                ('numeroRecidencia', models.ImageField(upload_to='')),
                ('bairro', models.CharField(max_length=100)),
                ('estadoUF', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('cidade', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
            ],
        ),
    ]
