# Generated by Django 5.0 on 2024-08-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ptts_ouvidoria_maria_de_nazare",
            name="feedback",
            field=models.TextField(),
        ),
    ]
