# Generated by Django 5.0 on 2024-08-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0002_alter_ptts_ouvidoria_maria_de_nazare_feedback"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conselho_tutelar",
            options={"verbose_name": "Conselho Tutelar"},
        ),
        migrations.AlterModelOptions(
            name="cultura",
            options={"verbose_name": "Cultura"},
        ),
        migrations.AlterModelOptions(
            name="familia_acolhedora",
            options={"verbose_name": "Família Acolhedora"},
        ),
        migrations.AlterModelOptions(
            name="ptts_ouvidoria_maria_de_nazare",
            options={"verbose_name": "PTTS - Ouvidoria - Maria de Nazaré"},
        ),
        migrations.AddField(
            model_name="familia_acolhedora",
            name="bairro",
            field=models.CharField(default="null", max_length=150),
        ),
        migrations.AddField(
            model_name="familia_acolhedora",
            name="bem_maior",
            field=models.TextField(default="null"),
        ),
        migrations.AddField(
            model_name="familia_acolhedora",
            name="celular",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="familia_acolhedora",
            name="cep",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="familia_acolhedora",
            name="cidade",
            field=models.CharField(default="null", max_length=150),
        ),
        migrations.AddField(
            model_name="familia_acolhedora",
            name="complemento",
            field=models.CharField(default="null", max_length=200),
        ),
        migrations.AddField(
            model_name="familia_acolhedora",
            name="cpf",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="familia_acolhedora",
            name="data_nascimneto",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="familia_acolhedora",
            name="email",
            field=models.CharField(default="null", max_length=150),
        ),
        migrations.AddField(
            model_name="familia_acolhedora",
            name="endereco",
            field=models.CharField(default="null", max_length=300),
        ),
        migrations.AddField(
            model_name="familia_acolhedora",
            name="genero_acolhimento",
            field=models.CharField(default="null", max_length=20),
        ),
        migrations.AddField(
            model_name="familia_acolhedora",
            name="idade",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="familia_acolhedora",
            name="numero_residencia",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="familia_acolhedora",
            name="ponto_referencia",
            field=models.CharField(default="null", max_length=200),
        ),
        migrations.AddField(
            model_name="familia_acolhedora",
            name="preferencia_perfil",
            field=models.TextField(default="null"),
        ),
        migrations.AddField(
            model_name="familia_acolhedora",
            name="renda",
            field=models.CharField(default="null", max_length=5),
        ),
        migrations.AddField(
            model_name="familia_acolhedora",
            name="renda_aproximada",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AddField(
            model_name="familia_acolhedora",
            name="residente",
            field=models.CharField(default="null", max_length=5),
        ),
        migrations.AddField(
            model_name="familia_acolhedora",
            name="rg",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="familia_acolhedora",
            name="sabendo_servico",
            field=models.CharField(default="null", max_length=150),
        ),
        migrations.AddField(
            model_name="familia_acolhedora",
            name="telefone",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="familia_acolhedora",
            name="uf",
            field=models.CharField(default="null", max_length=10),
        ),
        migrations.AlterField(
            model_name="familia_acolhedora",
            name="nome",
            field=models.CharField(default="null", max_length=100),
        ),
    ]
