# Generated by Django 5.0 on 2024-08-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0005_alter_familia_acolhedora_bairro_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familia_acolhedora",
            name="data_nascimneto",
            field=models.IntegerField(default=0),
        ),
    ]
