# Generated by Django 5.0 on 2024-08-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0009_alter_familia_acolhedora_data_nascimneto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conselho_tutelar_cristo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao_denuncia", models.CharField(max_length=300)),
                ("endereco_aconteceu", models.CharField(max_length=300)),
                ("descricao", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "Conselho Tutelar Cristo",
            },
        ),
        migrations.CreateModel(
            name="Conselho_tutelar_mangabeira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao_denuncia", models.CharField(max_length=300)),
                ("endereco_aconteceu", models.CharField(max_length=300)),
                ("descricao", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "Conselho Tutelar Mangabeira",
            },
        ),
        migrations.CreateModel(
            name="Conselho_tutelar_norte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao_denuncia", models.CharField(max_length=300)),
                ("endereco_aconteceu", models.CharField(max_length=300)),
                ("descricao", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "Conselho Tutelar Norte",
            },
        ),
        migrations.CreateModel(
            name="Conselho_tutelar_praia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao_denuncia", models.CharField(max_length=300)),
                ("endereco_aconteceu", models.CharField(max_length=300)),
                ("descricao", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "Conselho Tutelar Praia",
            },
        ),
        migrations.CreateModel(
            name="Conselho_tutelar_sudeste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao_denuncia", models.CharField(max_length=300)),
                ("endereco_aconteceu", models.CharField(max_length=300)),
                ("descricao", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "Conselho Tutelar Sudeste",
            },
        ),
        migrations.CreateModel(
            name="Conselho_tutelar_sul",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao_denuncia", models.CharField(max_length=300)),
                ("endereco_aconteceu", models.CharField(max_length=300)),
                ("descricao", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "Conselho Tutelar Sul",
            },
        ),
        migrations.CreateModel(
            name="Conselho_tutelar_valentina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=500)),
                ("endereco_aconteceu", models.CharField(max_length=300)),
            ],
            options={
                "verbose_name": "Conselho Tutelar Valentina",
            },
        ),
    ]
