# Generated by Django 5.0 on 2024-08-23 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0012_alter_familia_acolhedora_forms_bairro_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="familia_acolhedora_forms",
            options={"verbose_name": "Formulario Família Acolhedora"},
        ),
    ]
