# Generated by Django 5.0 on 2024-08-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consulta_Ginecologista_LGBT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomeSocial", models.CharField(max_length=100)),
                ("nomeRegistro", models.CharField(max_length=100)),
                ("nomeEmergencia", models.CharField(max_length=100)),
                ("cidadeOneReside", models.CharField(max_length=100)),
                ("endereco", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "identidadeGenero",
                    models.CharField(
                        choices=[
                            ("F", "Feminino"),
                            ("M", "Masculino"),
                            ("NB", "Não-Binário"),
                            ("MC", "Mulher Cis"),
                            ("HC", "Homem Cis"),
                            ("MT", "Mulher Trans"),
                            ("HT", "Homem Trans"),
                            ("T", "Travesti"),
                            ("O", "Outro"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "orientacaoSexual",
                    models.CharField(
                        choices=[
                            ("F", "Feminino"),
                            ("M", "Masculino"),
                            ("NB", "Não-Binário"),
                            ("MC", "Mulher Cis"),
                            ("HC", "Homem Cis"),
                            ("MT", "Mulher Trans"),
                            ("HT", "Homem Trans"),
                            ("T", "Travesti"),
                            ("O", "Outro"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "cor",
                    models.CharField(
                        choices=[
                            ("B", "Branco"),
                            ("P", "Preto"),
                            ("I", "Indígena"),
                            ("A", "Amarelo"),
                            ("Q", "Quilombola"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "estadoCivil",
                    models.CharField(
                        choices=[
                            ("S", "Solteiro"),
                            ("C", "Casado"),
                            ("D", "Divorciado"),
                            ("V", "Viúvo"),
                            ("U", "União Estável"),
                        ],
                        max_length=2,
                    ),
                ),
                ("possuiDeficiencia", models.BooleanField()),
                (
                    "tipoDeficiencia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("F", "Física"),
                            ("M", "Mental"),
                            ("A", "Auditiva"),
                            ("V", "Visual"),
                            ("O", "Outra"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "tipoViolencia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("F", "Física"),
                            ("P", "Psicológica"),
                            ("S", "Sexual"),
                            ("M", "Moral"),
                            ("E", "Econômica"),
                            ("O", "Outra"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "motivoViolencia",
                    models.CharField(
                        choices=[
                            ("S", "Sexismo"),
                            ("L", "LGBTfobia"),
                            ("R", "Racismo"),
                            ("I", "Intolerância Religiosa"),
                            ("X", "Xenofobia"),
                            ("CG", "Conflito Geracional"),
                            ("SR", "Situação de Rua"),
                            ("D", "Deficiência"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "grauParentesco",
                    models.CharField(
                        choices=[
                            ("N", "Não Sofri Violência"),
                            ("P", "Pai"),
                            ("M", "Mãe"),
                            ("C", "Conjuge"),
                            ("E", "Ex-conjuge"),
                            ("N", "Namorado (a)"),
                            ("X", "Ex-namorado (a)"),
                            ("A", "Amigo"),
                            ("F", "Filho"),
                            ("I", "Irmão"),
                            ("D", "Desconhecido"),
                            ("O", "Outro"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "localViolencia",
                    models.CharField(
                        choices=[
                            ("D", "Domicílio"),
                            ("T", "Trabalho"),
                            ("E", "Escola"),
                            ("R", "Rua"),
                            ("O", "Outro"),
                        ],
                        max_length=1,
                    ),
                ),
                ("tenativadeSuicidio", models.BooleanField()),
                ("cpf", models.CharField(max_length=100)),
                ("dataNascimento", models.DateField()),
            ],
            options={
                "verbose_name": "Consulta Ginecologista LGBT",
            },
        ),
        migrations.CreateModel(
            name="Denuncia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=100)),
                ("horarioFuncionamento", models.CharField(max_length=100)),
                ("endereco", models.CharField(max_length=100)),
                ("bairro", models.CharField(max_length=100)),
                ("pontoReferencia", models.CharField(max_length=100)),
                ("horaDaDenuncia", models.CharField(max_length=100)),
                ("motivoDenuncia", models.TextField()),
                ("cidadeDaDenuncia", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Denúncia",
            },
        ),
        migrations.CreateModel(
            name="Vacinacao_Domiciliar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telefone", models.CharField(max_length=100)),
                ("cep", models.CharField(max_length=100)),
                ("bairro", models.CharField(max_length=100)),
                ("rua", models.CharField(max_length=100)),
                ("numeroCasa", models.IntegerField()),
                ("pontoReferencia", models.CharField(max_length=100)),
                ("dataNascimento", models.DateField()),
            ],
            options={
                "verbose_name": "Vacinação Domiciliar",
            },
        ),
    ]
