# Generated by Django 5.0 on 2024-08-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saude", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacinacao_domiciliar",
            name="telefone",
            field=models.CharField(max_length=15),
        ),
    ]
