# Generated by Django 5.0 on 2024-08-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saude", "0002_alter_vacinacao_domiciliar_telefone"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemedioEmCasa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("numeroCNS", models.CharField(max_length=100)),
                ("unidadeSaude", models.CharField(max_length=100)),
                ("endereco", models.CharField(max_length=100)),
                ("bairro", models.CharField(max_length=100)),
                ("cidade", models.CharField(max_length=100)),
                ("telefone", models.CharField(max_length=15)),
                ("estadoUF", models.CharField(max_length=2)),
                ("cep", models.CharField(max_length=100)),
                (
                    "pacienteAcamado",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não")], max_length=1
                    ),
                ),
                ("dataNascimento", models.DateField()),
            ],
            options={
                "verbose_name": "Remédio em Casa",
            },
        ),
        migrations.CreateModel(
            name="RenovacaoReceita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", models.CharField(max_length=100)),
                ("rg", models.CharField(max_length=100)),
                ("endereco", models.CharField(max_length=100)),
                ("pontoReferencia", models.CharField(max_length=100)),
            ],
        ),
    ]
