# Generated by Django 5.0 on 2024-08-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saude", "0003_remedioemcasa_renovacaoreceita"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exames",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("sus", models.CharField(max_length=100)),
                (
                    "tipoExame",
                    models.CharField(
                        choices=[
                            ("E", "Ecocardiograma"),
                            ("R", "Ressonância Magnética"),
                            ("T", "Tomografia Computadorizada"),
                            ("U", "Ultrassonografia"),
                            ("M", "Mamografia"),
                            ("P", "Papanicolau"),
                            ("H", "Hemograma"),
                            ("G", "Glicemia"),
                        ],
                        max_length=2,
                    ),
                ),
                ("informacoesAdicionais", models.TextField()),
                ("telefone", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="SoliciteSuaCirugia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("sus", models.CharField(max_length=100)),
                (
                    "tipoExame",
                    models.CharField(
                        choices=[
                            ("E", "Ecocardiograma"),
                            ("R", "Ressonância Magnética"),
                            ("T", "Tomografia Computadorizada"),
                            ("U", "Ultrassonografia"),
                            ("M", "Mamografia"),
                            ("P", "Papanicolau"),
                            ("H", "Hemograma"),
                            ("G", "Glicemia"),
                        ],
                        max_length=2,
                    ),
                ),
                ("informacoesAdicionais", models.TextField()),
            ],
        ),
    ]
