# Generated by Django 5.0 on 2024-08-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saude", "0005_examecitopatologico_gastroenterologista"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consulta_ginecologista_lgbt",
            options={"verbose_name": "LGBT - Consulta Ginecologista LGBT"},
        ),
        migrations.AlterModelOptions(
            name="denuncia",
            options={"verbose_name": "Vigilancia Sanitaria - Denúncia"},
        ),
        migrations.AlterModelOptions(
            name="examecitopatologico",
            options={"verbose_name": "LGBT - Exame Citopatológico"},
        ),
        migrations.AlterModelOptions(
            name="exames",
            options={"verbose_name": "Prefeitura opera mais - Exames"},
        ),
        migrations.AlterModelOptions(
            name="gastroenterologista",
            options={"verbose_name": "LGBT - Gastroenterologista"},
        ),
        migrations.AlterModelOptions(
            name="renovacaoreceita",
            options={"verbose_name": "Remédio em casa - Renovação de Receita"},
        ),
        migrations.AlterModelOptions(
            name="solicitesuacirugia",
            options={"verbose_name": "Prefeitura opera mais - Solicite sua Cirurgia"},
        ),
        migrations.AddField(
            model_name="gastroenterologista",
            name="nivelEscolaridade",
            field=models.CharField(
                choices=[
                    ("A", "Analfabeto"),
                    ("F", "Fundamental"),
                    ("M", "Médio"),
                    ("S", "Superior"),
                    ("P", "Pós-Graduação"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gastroenterologista",
            name="tipoDeficiencia",
            field=models.CharField(
                blank=True,
                choices=[
                    ("F", "Física"),
                    ("M", "Mental"),
                    ("A", "Auditiva"),
                    ("V", "Visual"),
                    ("O", "Outra"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gastroenterologista",
            name="trabalhoSituacao",
            field=models.CharField(
                choices=[
                    ("E", "Empregado"),
                    ("D", "Desempregado"),
                    ("A", "Aposentado"),
                    ("E", "Empreendedor"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="consulta_ginecologista_lgbt",
            name="possuiDeficiencia",
            field=models.CharField(choices=[("S", "Sim"), ("N", "Não")], max_length=1),
        ),
        migrations.AlterField(
            model_name="consulta_ginecologista_lgbt",
            name="tenativadeSuicidio",
            field=models.CharField(choices=[("S", "Sim"), ("N", "Não")], max_length=1),
        ),
        migrations.AlterField(
            model_name="examecitopatologico",
            name="recebeBeneficio",
            field=models.CharField(
                choices=[
                    ("B", "Bolsa Família"),
                    ("A", "Aposentadoria"),
                    ("S", "Seguro Desemprego"),
                    ("O", "Outro"),
                    ("U", "Bolsa Universidade"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="examecitopatologico",
            name="tipoDeficiencia",
            field=models.CharField(
                choices=[
                    ("F", "Física"),
                    ("M", "Mental"),
                    ("A", "Auditiva"),
                    ("V", "Visual"),
                    ("O", "Outra"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="gastroenterologista",
            name="possuiDeficiencia",
            field=models.CharField(choices=[("S", "Sim"), ("N", "Não")], max_length=1),
        ),
    ]
