# Generated by Django 5.0 on 2024-08-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saude", "0006_alter_consulta_ginecologista_lgbt_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartaoSus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "cor",
                    models.CharField(
                        choices=[
                            ("B", "Branco"),
                            ("P", "Preto"),
                            ("I", "Indígena"),
                            ("A", "Amarelo"),
                            ("Q", "Quilombola"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cartão SUS",
            },
        ),
    ]
