# Generated by Django 5.0 on 2024-08-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saude", "0007_cartaosus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartaosus",
            options={"verbose_name": "Cartão SUS - Solicite seu cartão SUS"},
        ),
        migrations.AlterField(
            model_name="consulta_ginecologista_lgbt",
            name="cpf",
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name="examecitopatologico",
            name="cpf",
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name="gastroenterologista",
            name="cpf",
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name="remedioemcasa",
            name="estadoUF",
            field=models.CharField(
                choices=[
                    ("AC", "Acre"),
                    ("AL", "Alagoas"),
                    ("AP", "Amapá"),
                    ("AM", "Amazonas"),
                    ("BA", "Bahia"),
                    ("CE", "Ceará"),
                    ("DF", "Distrito Federal"),
                    ("ES", "Espírito Santo"),
                    ("GO", "Goiás"),
                    ("MA", "Maranhão"),
                    ("MT", "Mato Grosso"),
                    ("MS", "Mato Grosso do Sul"),
                    ("MG", "Minas Gerais"),
                    ("PA", "Pará"),
                    ("PB", "Paraíba"),
                    ("PR", "Paraná"),
                    ("PE", "Pernambuco"),
                    ("PI", "Piauí"),
                    ("RJ", "Rio de Janeiro"),
                    ("RN", "Rio Grande do Norte"),
                    ("RS", "Rio Grande do Sul"),
                    ("RO", "Rondônia"),
                    ("RR", "Roraima"),
                    ("SC", "Santa Catarina"),
                    ("SP", "São Paulo"),
                    ("SE", "Sergipe"),
                    ("TO", "Tocantins"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="renovacaoreceita",
            name="cpf",
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name="renovacaoreceita",
            name="rg",
            field=models.CharField(max_length=14),
        ),
    ]
