# Generated by Django 5.0 on 2024-08-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saude", "0008_alter_cartaosus_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denuncia",
            name="horarioFuncionamento",
            field=models.TimeField(),
        ),
    ]
