# Generated by Django 5.0 on 2024-08-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saude", "0010_alter_denuncia_horadadenuncia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remedioemcasa",
            name="cep",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="vacinacao_domiciliar",
            name="cep",
            field=models.CharField(max_length=10),
        ),
    ]
