# Generated by Django 5.0 on 2024-08-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saude", "0011_alter_remedioemcasa_cep_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remedioemcasa",
            name="numeroCNS",
            field=models.IntegerField(max_length=15),
        ),
    ]
