# Generated by Django 5.0 on 2024-08-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saude", "0012_alter_remedioemcasa_numerocns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remedioemcasa",
            name="numeroCNS",
            field=models.IntegerField(),
        ),
    ]
