# Generated by Django 5.0 on 2024-09-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saude", "0014_exameendocrinologia"),
    ]

    operations = [
        migrations.AddField(
            model_name="denuncia",
            name="status",
            field=models.CharField(
                choices=[
                    ("Aberto", "Aberto"),
                    ("Cancelado", "Cancelado"),
                    ("Fechado", "Fechado"),
                    ("Em andamento", "Em andamento"),
                ],
                default="Em andamento",
                max_length=19,
            ),
        ),
    ]
