# Generated by Django 5.0 on 2024-09-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saude", "0015_denuncia_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartaosus",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Aberto", "Aberto"),
                    ("Cancelado", "Cancelado"),
                    ("Fechado", "Fechado"),
                    ("Em andamento", "Em andamento"),
                ],
                default="Em andamento",
                max_length=19,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="consulta_ginecologista_lgbt",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Aberto", "Aberto"),
                    ("Cancelado", "Cancelado"),
                    ("Fechado", "Fechado"),
                    ("Em andamento", "Em andamento"),
                ],
                default="Em andamento",
                max_length=19,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="examecitopatologico",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Aberto", "Aberto"),
                    ("Cancelado", "Cancelado"),
                    ("Fechado", "Fechado"),
                    ("Em andamento", "Em andamento"),
                ],
                default="Em andamento",
                max_length=19,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="exameendocrinologia",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Aberto", "Aberto"),
                    ("Cancelado", "Cancelado"),
                    ("Fechado", "Fechado"),
                    ("Em andamento", "Em andamento"),
                ],
                default="Em andamento",
                max_length=19,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="exames",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Aberto", "Aberto"),
                    ("Cancelado", "Cancelado"),
                    ("Fechado", "Fechado"),
                    ("Em andamento", "Em andamento"),
                ],
                default="Em andamento",
                max_length=19,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gastroenterologista",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Aberto", "Aberto"),
                    ("Cancelado", "Cancelado"),
                    ("Fechado", "Fechado"),
                    ("Em andamento", "Em andamento"),
                ],
                default="Em andamento",
                max_length=19,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="remedioemcasa",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Aberto", "Aberto"),
                    ("Cancelado", "Cancelado"),
                    ("Fechado", "Fechado"),
                    ("Em andamento", "Em andamento"),
                ],
                default="Em andamento",
                max_length=19,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="renovacaoreceita",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Aberto", "Aberto"),
                    ("Cancelado", "Cancelado"),
                    ("Fechado", "Fechado"),
                    ("Em andamento", "Em andamento"),
                ],
                default="Em andamento",
                max_length=19,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="solicitesuacirugia",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Aberto", "Aberto"),
                    ("Cancelado", "Cancelado"),
                    ("Fechado", "Fechado"),
                    ("Em andamento", "Em andamento"),
                ],
                default="Em andamento",
                max_length=19,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vacinacao_domiciliar",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Aberto", "Aberto"),
                    ("Cancelado", "Cancelado"),
                    ("Fechado", "Fechado"),
                    ("Em andamento", "Em andamento"),
                ],
                default="Em andamento",
                max_length=19,
                null=True,
            ),
        ),
    ]
