# Generated by Django 5.1 on 2024-08-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CataTreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Cata-Treco',
            },
        ),
        migrations.CreateModel(
            name='ColetaDeAnimaisMortos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Coleta de Animais Mortos',
            },
        ),
        migrations.CreateModel(
            name='ColetaDePoda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Coleta de Poda',
            },
        ),
        migrations.CreateModel(
            name='ColetaDeResiduosDiversificados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Coleta de Resíduos Diversificados',
            },
        ),
        migrations.CreateModel(
            name='ColetaSeletiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrisao', models.TextField()),
            ],
            options={
                'verbose_name': 'Coleta Seletiva (Condomínio/Empresas)',
            },
        ),
        migrations.CreateModel(
            name='DenunciaDeDescarteIrregularDeResiduos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Denúncia De Descarte Irregular De Resíduos',
            },
        ),
        migrations.CreateModel(
            name='FalhaNaColetaDomiciliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Falha na Coleta Domiciliar',
            },
        ),
        migrations.CreateModel(
            name='LimpezaDePropriosMunicipais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Limpeza de Próprios Municipais',
            },
        ),
        migrations.CreateModel(
            name='TerrenoSemConservacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Terreno sem consevacão',
            },
        ),
        migrations.CreateModel(
            name='VarricaoDeLogradourosPublicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Varrição de Logradouros Públicos',
            },
        ),
    ]
