# Generated by Django 5.1 on 2024-08-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Denuncia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=250)),
                ("nome", models.CharField(max_length=150)),
                ("cpf", models.CharField(max_length=14)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("F", "Feminino"), ("M", "Masculino"), ("O", "Outro")],
                        max_length=2,
                    ),
                ),
                ("cep", models.CharField(max_length=10)),
                ("rua", models.CharField(max_length=50)),
                ("bairro", models.CharField(max_length=15)),
                ("cidade", models.CharField(max_length=20)),
                ("telefone_whatsapp", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=75)),
                ("razao_social", models.CharField(max_length=200)),
                ("telefoneFornecedor", models.CharField(max_length=20)),
                ("nomeFornencedor", models.CharField(max_length=150)),
                ("enderecoFornecedor", models.CharField(max_length=200)),
                ("cnpj", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Duvida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("cpf", models.CharField(max_length=14)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("F", "Feminino"), ("M", "Masculino"), ("O", "Outro")],
                        max_length=2,
                    ),
                ),
                ("cep", models.CharField(max_length=10)),
                ("rua", models.CharField(max_length=50)),
                ("bairro", models.CharField(max_length=15)),
                ("cidade", models.CharField(max_length=20)),
                ("telefone_whatsapp", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=75)),
                ("razao_social", models.CharField(max_length=200)),
                ("telefone_fornecedor", models.CharField(max_length=20)),
                ("nome_fts_fncd", models.CharField(max_length=150)),
                ("endereco_fornecedor", models.CharField(max_length=200)),
                ("descricao", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="EmissaoBoleto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("cpf", models.CharField(max_length=14)),
                ("email", models.CharField(max_length=75)),
                ("telefone", models.CharField(max_length=20)),
                ("cnpj", models.CharField(max_length=20)),
                ("observacoes", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="PaoLeite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("dataNascimento", models.DateField()),
                ("idade", models.IntegerField()),
                ("telefone", models.CharField(max_length=20)),
                ("cpf", models.CharField(max_length=14)),
                ("endereco", models.CharField(max_length=200)),
                ("bairro", models.CharField(max_length=20)),
                (
                    "carteiraTrabalhoAss",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não")], max_length=1
                    ),
                ),
                (
                    "possuiDeficiencia",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não")], max_length=1
                    ),
                ),
                (
                    "estadoCivil",
                    models.CharField(
                        choices=[
                            ("S", "Solteiro"),
                            ("C", "Casado"),
                            ("D", "Divorciado"),
                            ("V", "Viúvo"),
                            ("U", "União Estável"),
                        ],
                        max_length=1,
                    ),
                ),
                ("numeroNis", models.CharField(max_length=50)),
                (
                    "possuiBolsaFamilia",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não")], max_length=1
                    ),
                ),
                (
                    "possuiCartaoAlimentacao",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não")], max_length=1
                    ),
                ),
                (
                    "concordoTermos",
                    models.CharField(choices=[("S", "Sim")], max_length=1),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reclamacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("cpf", models.CharField(max_length=14)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("F", "Feminino"), ("M", "Masculino"), ("O", "Outro")],
                        max_length=2,
                    ),
                ),
                ("cep", models.CharField(max_length=10)),
                ("rua", models.CharField(max_length=50)),
                ("bairro", models.CharField(max_length=15)),
                ("cidade", models.CharField(max_length=20)),
                ("telefone_whatsapp", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=75)),
                ("razao_social", models.CharField(max_length=200)),
                ("telefone_fornecedor", models.CharField(max_length=20)),
                ("nome_fts_fncd", models.CharField(max_length=150)),
                ("endereco_fornecedor", models.CharField(max_length=200)),
                ("descricao", models.CharField(max_length=250)),
            ],
        ),
    ]
