# Generated by Django 5.1 on 2024-08-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos2", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denuncia",
            name="sexo",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="duvida",
            name="sexo",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="paoleite",
            name="carteiraTrabalhoAss",
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name="paoleite",
            name="concordoTermos",
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name="paoleite",
            name="dataNascimento",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="paoleite",
            name="estadoCivil",
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name="paoleite",
            name="possuiBolsaFamilia",
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name="paoleite",
            name="possuiCartaoAlimentacao",
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name="paoleite",
            name="possuiDeficiencia",
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name="reclamacao",
            name="sexo",
            field=models.CharField(max_length=3),
        ),
    ]
