# Generated by Django 5.1 on 2024-08-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventos2", "0002_alter_denuncia_sexo_alter_duvida_sexo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="denuncia",
            name="email",
        ),
    ]
