# Generated by Django 5.1 on 2024-08-23 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventos2", "0003_remove_denuncia_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="denuncia",
            old_name="enderecoFornecedor",
            new_name="endereco_fornecedor",
        ),
        migrations.RenameField(
            model_name="denuncia",
            old_name="nomeFornencedor",
            new_name="nome_fornencedor",
        ),
        migrations.RenameField(
            model_name="denuncia",
            old_name="telefoneFornecedor",
            new_name="telefone_fornecedor",
        ),
    ]
