# Generated by Django 5.1 on 2024-08-23 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "eventos2",
            "0004_rename_enderecofornecedor_denuncia_endereco_fornecedor_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="denuncia",
            old_name="nome_fornencedor",
            new_name="nome_fornecedor",
        ),
    ]
