# Generated by Django 5.1 on 2024-09-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos2", "0005_rename_nome_fornencedor_denuncia_nome_fornecedor"),
    ]

    operations = [
        migrations.AddField(
            model_name="denuncia",
            name="status",
            field=models.CharField(default="em andamento", max_length=12),
        ),
    ]
