# Generated by Django 5.1 on 2024-09-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos2", "0006_denuncia_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denuncia",
            name="sexo",
            field=models.CharField(max_length=10),
        ),
    ]
