# Generated by Django 5.1 on 2024-08-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "licenciamento_2",
            "0002_sedrub_cpf_sedrub_endereco_sedrub_ligação_de_energia_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sedrub",
            name="CPF",
            field=models.IntegerField(max_length=11),
        ),
    ]
