# Generated by Django 5.1 on 2024-08-23 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("licenciamento_2", "0009_autorização_uso_de_solo_eventual_requerente"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="autorização_uso_de_solo_eventual",
            name="Requerente",
        ),
    ]
