# Generated by Django 5.1 on 2024-08-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenciamento_2", "0012_autorização_uso_de_solo_eventual_requerente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autorização_uso_de_solo_eventual",
            name="Requerente",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
