# Generated by Django 5.1 on 2024-08-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenciamento_2", "0013_alter_autorização_uso_de_solo_eventual_requerente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Atualização_Cadatral_Dos_Quiosques",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Caixa1", models.CharField(default=None, max_length=200)),
                ("Nome", models.CharField(default=None, max_length=200)),
                ("CPF", models.IntegerField(default=None)),
                ("Telefone", models.IntegerField(default=None)),
                ("Email", models.EmailField(default=None, max_length=254)),
                ("Endereco_1", models.CharField(default=None, max_length=200)),
                ("Endereco_2", models.CharField(default=None, max_length=200)),
                ("Logradouro", models.CharField(default=None, max_length=200)),
                ("Bairro", models.CharField(default=None, max_length=200)),
                ("Tipo_Equipamento", models.CharField(default=None, max_length=200)),
                ("Numero_Box", models.IntegerField(default=None)),
                ("Quadra_ou_ilha", models.CharField(default=None, max_length=200)),
                ("Tipo_Construcao", models.CharField(default=None, max_length=200)),
                ("Area_Ocupada", models.IntegerField(default=None)),
                ("Tempo_Ocupa", models.DateField(default=None, max_length=200)),
                ("Validade_Permissao", models.DateField(default=None, max_length=200)),
                ("Estrutura_Utilizada", models.CharField(default=None, max_length=200)),
                ("Atividade_Economica", models.CharField(default=None, max_length=200)),
                ("Infor", models.CharField(default=None, max_length=200)),
            ],
        ),
    ]
