# Generated by Django 5.1 on 2024-08-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "licenciamento_2",
            "0015_rename_atualização_cadatral_dos_quiosques_atualizacao_cadatral_dos_quiosques_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="atualizacao_cadatral_dos_quiosques",
            name="Descricao",
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name="atualizacao_cadatral_dos_quiosques",
            name="Tempo_Ocupa",
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="atualizacao_cadatral_dos_quiosques",
            name="Validade_Permissao",
            field=models.IntegerField(default=None),
        ),
    ]
