# Generated by Django 5.1 on 2024-08-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "licenciamento_2",
            "0018_alter_atualizacao_cadatral_dos_quiosques_tipo_construcao",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="atualizacao_cadatral_dos_quiosques",
            old_name="Infor",
            new_name="Infor_1",
        ),
    ]
