# Generated by Django 5.1 on 2024-08-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "licenciamento_2",
            "0019_rename_infor_atualizacao_cadatral_dos_quiosques_infor_1",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SEDRUB",
            new_name="SEDRUB_Autorizacao_Uso_Solo_Comercial",
        ),
    ]
