# Generated by Django 5.1.1 on 2024-09-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenciamento_2", "0020_rename_sedrub_sedrub_autorizacao_uso_solo_comercial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sedrub_autorizacao_uso_solo_comercial",
            name="Status",
            field=models.CharField(default="Em Andamento", max_length=12),
        ),
    ]
