# Generated by Django 5.1 on 2024-08-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Desmoronamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Palestras_Para_Instituicoes_De_Ensino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Registro_De_Ocorrencia_De_Desastre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Secretaria_De_Seguranca_Urbana_Cidadania",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Solicitacao_De_Guarnicao_Para_Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Solicitacao_De_Rondas_Da_Guarda_Municipal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Solicitacao_De_Visitorias_Preventivas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Teatro_De_Fantoches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telefone_do_resposavel", models.TextField(max_length=11)),
                ("email", models.TextField(max_length=300)),
                ("local_da_apresentacao", models.TextField(verbose_name=300)),
                ("cep", models.TextField(max_length=9)),
                ("bairro", models.TextField(max_length=200)),
                ("ponto_de_referencia", models.TextField(max_length=200)),
                ("publico_estimado", models.IntegerField()),
                ("tema_da_apresentacao", models.TextField(max_length=200)),
                (
                    "possui_microfone",
                    models.TextField(
                        choices=[("S", "Sim"), ("N", "Não")], max_length=1
                    ),
                ),
                (
                    "possui_caixa_de_som",
                    models.TextField(
                        choices=[("S", "Sim"), ("N", "Não")], max_length=1
                    ),
                ),
            ],
        ),
    ]
