# Generated by Django 5.1 on 2024-08-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seguranca", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Denuncie_aqui",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bairro_do_local_da_denuncia", models.TextField(max_length=300)),
                ("rua_do_local_da_denuncia", models.TextField(max_length=300)),
                (
                    "ponto_de_referencia_do_local_da_denuncia",
                    models.TextField(max_length=200),
                ),
                ("cep_do_local_da_denuncia", models.TextField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name="alagamento",
            name="descricao",
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="desmoronamento",
            name="descricao",
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="palestras_para_instituicoes_de_ensino",
            name="descricao",
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="registro_de_ocorrencia_de_desastre",
            name="descricao",
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="secretaria_de_seguranca_urbana_cidadania",
            name="descricao",
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="solicitacao_de_guarnicao_para_evento",
            name="descricao",
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="solicitacao_de_rondas_da_guarda_municipal",
            name="descricao",
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="solicitacao_de_visitorias_preventivas",
            name="descricao",
            field=models.TextField(max_length=2000),
        ),
    ]
