# Generated by Django 5.1 on 2024-08-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seguranca", "0002_denuncie_aqui_alter_alagamento_descricao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teatro_de_fantoches",
            name="possui_caixa_de_som",
            field=models.TextField(max_length=3),
        ),
        migrations.AlterField(
            model_name="teatro_de_fantoches",
            name="possui_microfone",
            field=models.TextField(max_length=3),
        ),
    ]
