# Generated by Django 5.1 on 2024-08-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seguranca", "0003_alter_teatro_de_fantoches_possui_caixa_de_som_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teatro_de_fantoches",
            name="rua",
            field=models.TextField(default="", max_length=200),
        ),
    ]
