# Generated by Django 5.1 on 2024-08-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seguranca", "0004_teatro_de_fantoches_rua"),
    ]

    operations = [
        migrations.AddField(
            model_name="denuncie_aqui",
            name="observacoes",
            field=models.TextField(default="", max_length=1000),
        ),
    ]
