# Generated by Django 5.1.1 on 2024-09-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seguranca", "0006_palestras_para_instituicoes_de_ensino_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="palestras_para_instituicoes_de_ensino",
            name="status",
            field=models.CharField(default="ABERTO", max_length=30),
        ),
    ]
